### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by pavelzarubin** [stepa1000/echo-bot-template#11]
Ormolu не применялся.
Смотри [требования](https://coda.io/@metalamp/education/5-16)

**Comment by pavelzarubin** [comment]
Каким форматером  все таки пользуешься?

**Comment by stepa1000** [comment]
#19

**Comment by pavelzarubin** [comment]
Ормолу у меня до сих пор вносит правки.

**Comment by stepa1000** [comment]
#24
