### ISSUE TITLE
Лишние данные.

### ISSUE THREAD

**Issue by pavelzarubin** [stepa1000/echo-bot-template#12]
Ты когда получаешь обновления, парсишь некоторые лишние данные. Например ты собираешь, насколько я помню, информацию о форматировании, но текст возвращаешь уже без него. Тут как хочешь, либо вообще не парси эту часть, либо возвращай текст в исходном виде.
```haskell
data Entity = Entity
    { offsetEntity :: Int
    , lengthEntity :: Int
    , entityTypeEntity :: Text
    } deriving (Show)
```

**Comment by stepa1000** [comment]
убрал.

**Comment by pavelzarubin** [comment]
Там еще в типах есть поля, которые ты не используешь. Посмотри внимательно.

**Comment by pavelzarubin** [comment]
https://github.com/stepa1000/echo-bot-template/blob/55fbf455847147c9bb0bb501f5801ad08711331b/src/FrontEnd/Telegram/Data/GetUpdate.hs#L26

Вот например, там еще есть еще всякие флаги, размеры фото и прочее. Проверь, скорее всего при отправке сообщений они вообще не нужны.

**Comment by stepa1000** [comment]
#19
