### ISSUE TITLE
Небезопасные функции

### ISSUE THREAD

**Issue by pavelzarubin** [stepa1000/echo-bot-template#13]
Если файл с конфигом отсутствует, то у тебя некорректно завершается работа бота. Нужно это правильно обработать. Я бы на твоем месте использовал для конфигов пакет [configurator](https://hackage.haskell.org/package/configurator).

**Comment by stepa1000** [comment]
переписал конфиги с пакето yaml. Как именно обработать отцутствие конфигов?

**Comment by pavelzarubin** [comment]
Ну вообще просто должно быть выдано пользователю сообщение об отсутствии конфига. Если в конфиге нет каких либо полей, или они заданы неверно, об этом тоже должно быть сообщение. Не нужно чтобы вылетала ошибка сгенерированная кодом библиотек.

**Comment by stepa1000** [comment]
обязательно переписывать ошибки от yaml или будет достаточно от оберток избавиться.

**Comment by pavelzarubin** [comment]
Ну ты можешь отловить ошибки от yaml и просто выдать ошибку на экран. Главное чтобы пользователю было ясно, что произошло.

**Comment by stepa1000** [comment]
#17

**Comment by pavelzarubin** [comment]
Пр не закрывай до проверки, и связывай их с ишью

**Comment by pavelzarubin** [comment]
Отписал в пр

**Comment by stepa1000** [comment]
#18

**Comment by stepa1000** [comment]
https://github.com/stepa1000/echo-bot-template/blob/76ecc8b2c96e0b493aeefde083439173178d6bf9/src/ConfigBot.hs#L42-L64

**Comment by pavelzarubin** [comment]
А не проще ли тогда использовать `prettyPrintParseException`

**Comment by pavelzarubin** [comment]
Вообще я бы хотел чтоб ты свои ошибки написал, а не выводил то, что выдает библиотека. Но видишь тут проблема в том, что ты все таки используешь yaml. И например ты не можешь нормально обработать ошибку некорректного поля или данных, так как они все попадают под AesonException.

**Comment by stepa1000** [comment]
#19
