### ISSUE TITLE
Обработка ввода

### ISSUE THREAD

**Issue by pavelzarubin** [stepa1000/echo-bot-template#14]
https://github.com/stepa1000/echo-bot-template/blob/6995588f175dfdd0ccbddefb37da9b9b81a4bf5f/src/FrontEnd/Console.hs#L51-L53

Здесь лучше выдать сообщение о неправильном вводе.

**Comment by stepa1000** [comment]
сделал

**Comment by stepa1000** [comment]
https://github.com/stepa1000/echo-bot-template/blob/55fbf455847147c9bb0bb501f5801ad08711331b/src/FrontEnd/Console.hs#L48-L56

**Comment by pavelzarubin** [comment]
Хорошо, только меню с выбором числа, сделай читаемое. Ненужно выводить его в таком формате, достаточно обычного сообщения.

**Comment by stepa1000** [comment]
#19
