### ISSUE TITLE
Конфиг

### ISSUE THREAD

**Issue by pavelzarubin** [stepa1000/echo-bot-template#6]
Лучше не генерировать конфиг, а оставить шаблон конфига с описанием каждого поля.
Да и зачем 4 конфига? Можно все параметры хранить в одном.

**Comment by pavelzarubin** [comment]
Зачем в конфиге для телеграмма имя бота?

**Comment by stepa1000** [comment]
Что бы бот отличал свои сообщения от сообщений пользователя.

**Comment by paffel2** [comment]
Задай любое имя и посмотри как бот будет работать.

**Comment by pavelzarubin** [comment]
Задай любое имя бота в конфиге и посмотри, что будет

**Comment by pavelzarubin** [comment]
https://github.com/stepa1000/echo-bot-template/blob/6995588f175dfdd0ccbddefb37da9b9b81a4bf5f/src/FrontEnd/Telegram/Telegram.hs#L165-L166

у тебя эта фильтрация не используется вообще

**Comment by stepa1000** [comment]
убрал филтрацию и имя бота из конфигов

**Comment by pavelzarubin** [comment]
А пр где?

**Comment by pavelzarubin** [comment]
Описания полей конфига так и нет

**Comment by pavelzarubin** [comment]
Конфиг все еще генерируется. Что будем делать, если у меня винда и нет баша?

**Comment by stepa1000** [comment]
#19 добавил образец конфига, рядом с генерируемым.

**Comment by pavelzarubin** [comment]
Если есть образец, то генерация не нужна. Комментариев так и нет для каждого поля. Yaml комментарии поддерживает.

**Comment by pavelzarubin** [comment]
И не надо все исправления в одну ветку писать. Одно исправление - одна ветка - один пр.

**Comment by stepa1000** [comment]
#20

**Comment by stepa1000** [comment]
предложение исчерпано?
