### ISSUE TITLE
Выбор повторов

### ISSUE THREAD

**Issue by pavelzarubin** [stepa1000/echo-bot-template#7]
Почему когда мы отправляем запрос на смену повторов в телеграмм, нам приходит голосование?

**Comment by stepa1000** [comment]
Потамучто ссылка в требованиях бота введёт к poll https://core.telegram.org/bots/api#poll

**Comment by pavelzarubin** [comment]
Да, но там ссылка дана просто на bot api,  а не требование использовать poll. Ладно, оставим так. Можешь закрывать.
