### ISSUE TITLE
Лишний код

### ISSUE THREAD

**Issue by pavelzarubin** [stepa1000/echo-bot-template#8]
Как по мне папка Example лишняя.
Очень много лишних комментариев.
Все это нужно вычистить, либо написать что-то осознанное.
Если проблемы с английским и ты используешь vscode, то поставь плагин [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by stepa1000** [comment]
отчистил

**Comment by pavelzarubin** [comment]
https://github.com/stepa1000/echo-bot-template/blob/55fbf455847147c9bb0bb501f5801ad08711331b/src/FrontEnd/Telegram/Telegram.hs#L12

**Comment by pavelzarubin** [comment]
https://github.com/stepa1000/echo-bot-template/blob/55fbf455847147c9bb0bb501f5801ad08711331b/src/ConfigBot.hs#L14-L17

**Comment by pavelzarubin** [comment]
Там еще есть

**Comment by stepa1000** [comment]
#21

**Comment by stepa1000** [comment]
можно закрывать?

**Comment by pavelzarubin** [comment]
Да
