### ISSUE TITLE
Имена

### ISSUE THREAD

**Issue by pavelzarubin** [stepa1000/echo-bot-template#9]
Что за типы `Welcome9`, `Welcome10` и т. п.? Дай им нормальные имена. В коде много где присутствуют очень странные имена.

**Comment by pavelzarubin** [comment]
https://github.com/stepa1000/echo-bot-template/blob/f897342adce6b543f17b4fc110e8c2f95040f88d/src/FrontEnd/Telegram/Data/PollMessage.hs#L14

почему все-таки `Welcome`

**Comment by stepa1000** [comment]
утилита так сгенерировала.

**Comment by pavelzarubin** [comment]
Ну в общем, имена должны отражать суть функций или типов. Так что называй нормально. Слишком короткие имена тоже плохо, ну и длинные. Пройдись по всему коду и назови так, чтобы человек с первого взгляда мог понять, что где происходит.

**Comment by pavelzarubin** [comment]
> утилита так сгенерировала.

что за утилита?

**Comment by stepa1000** [comment]
https://jsonformatter.org/json-to-haskell

**Comment by pavelzarubin** [comment]
Ну в проде таким лучше не заниматься.

**Comment by stepa1000** [comment]
мне переменовать в Response?

**Comment by pavelzarubin** [comment]
Ну да. Все Welcome нужно убрать.

**Comment by pavelzarubin** [comment]
Вообще это не только Welcome касается, у тебя очень много имен состоящих из одной буквы. Все это нужно назвать развернуто.

**Comment by stepa1000** [comment]
у меня много типов состоящих из одного слова, нужен болие развёрнутое название?

**Comment by pavelzarubin** [comment]
Зависит от того, что они отражают. Если одного слова достаточно, то исправлять не нужно.

**Comment by stepa1000** [comment]
можно один пример где исправить.

**Comment by pavelzarubin** [comment]
https://github.com/stepa1000/echo-bot-template/blob/4f4e3004ededa482ea95a19530044011dfbafe3e/src/FrontEnd/Telegram/Data/GetUpdate.hs#L61-L66

Непонятно что за опция.

**Comment by stepa1000** [comment]
#22

**Comment by stepa1000** [comment]
можно закрывать?
